### ISSUE TITLE
I would like to read your paper PDF

### ISSUE THREAD

**Issue by dalaoplan** [SWY666/rPPG-DOHA#1]
Hello, I am very interested in your paper and I I would like to read your paper carefully.But I can't get this link through. Could you please provide a PDF of your paper on GitHub or send it to me? My email is zhipengli@stu.cqut.edu.cn Thank you for reading.

**Comment by SWY666** [comment]
Thanks for the interest! I have sent the original pdf to you via the email. If you have some other questions, I'm happy to help, ;)!
