### ISSUE TITLE
在驾驶场景下的效果如何

### ISSUE THREAD

**Issue by 408550969** [SWY666/rPPG-DOHA#2]
你好，TS-CAN、EfficientPhys等常用方法在驾驶场景下MAE都超过了12，请问DOHA能否在驾驶场景或者类似人脸平移的这种场景下使用，MAE是多少？

**Comment by SWY666** [comment]
你好，就驾驶场景而言（例如MR-NIRP数据集），我们在其路上开车、车库静止数据集上的MAE大概测量下来为3左右的MAE。更难的驾驶场景下我们还没做过测试，不过鉴于DOHA对于TS-CAN在中上难度数据集上的性能提升（例如VIPL-HR的v3,v8数据集），我们认为至少DOHA之后的方法在驾驶场景上的MAE会优于原本方法。

但是不得不说，DOHA的效果提升和其依附的网络框架（例如我们文中使用的变种TS-CAN）有一定关系（不同的框架提升效果不同）；而预处理（人脸提取、分割）和后处理（滤波等）同样也很重要。比如，**人脸平移**这个场景下预处理如果烂了最后的MAE会偏大。这是因为检测出来的人脸框也会跟着移动，这个人脸框中的人脸可能会受影响而出现瞬移（比如一会在右侧，一会人脸框动了人脸移到中间去了），这对于TS-CAN中的3d卷积层（主要是时域卷积）不是很友好。这种情况下可能需要用这类的人脸视频重新训练网络来保证心率的预测质量。

**Comment by 408550969** [comment]
非常感谢，请问目前的SOTA的方法是哪个？我想做的是驾驶场景，我看到有篇rPPG-MAE的论文，均说明了对运动场景的改善，请问是否有对比过rPPG-MAE？

**Comment by 408550969** [comment]
mask_list是怎么生成的，是用Skin-based attention module生成的吗，有这个moudle实现的代码吗？

**Comment by SWY666** [comment]
mask_list非常好生成，我们随便找一个皮肤提取算法就行，比如我用的就是像素法（简单来说，对每一个像素点的rgb值进行阈值分析，符合颜色条件的就是皮肤区域），opencv里有很多这种hh

**Comment by SWY666** [comment]
比如这篇博客里的方法：
https://blog.csdn.net/qq_14845119/article/details/121655002

**Comment by SWY666** [comment]
另外你说的SOTA方法（我之前还看到有这个问题的，但是怎么在github看不到了），我现在也不知道，有阵时间没搞这个领域了。我记得前几年都搞域外（测试集和训练集分布差异很大，比如NEST）或者自监督去了，这些都不怎么卷MAE了，但是我觉得这些方向更加贴近实际一点。

**Comment by 408550969** [comment]
谢谢！
